name: Terraform PR Checks

on:
  workflow_call:

jobs:
  check-commits:
    name: Conventional Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        id: semantic
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            refactor
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment if failed
        if: steps.semantic.outcome == 'failure'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: semantic-pr
          message: |
            ⚠️ This pull request title does not follow the [Conventional Commits](https://www.conventionalcommits.org/) format.

            Please update the title to follow the format: `<type>[!]: <short description>`

            Examples:

            ```
            feat: add new output for X
            fix: correct typo in Y
            refactor: restructure module Z
            chore: update GitHub actions version
            feat!: remove deprecated variable
            ```

            Use `!` after the type (e.g., `feat!:`) to indicate a **breaking change**. You can also include a `BREAKING CHANGE:` footer in the commit body if more context is needed.

      - name: Remove sticky comment if fixed
        if: steps.semantic.outcome == 'success'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: semantic-pr
          delete: true

  terraform-checks:
    name: Terraform Lint and Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - run: |
          tflint --init
          tflint

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform

  release:
    name: Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          release-type: terraform-module
